<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Usly.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Usly.Application\Usly.Application.csproj" />
    <ProjectReference Include="..\Usly.Infrastructure\Usly.Infrastructure.csproj" />
  </ItemGroup>
</Project>
